### PR TITLE
Support multiple latency threshold values

### PR DESCRIPTION
**Pull request by tjworks**
This allows the tool to track the latency performance at different latency threshold. For instance, one may be interested to see how many were under 10ms, how many were under 50ms, how many were under 100ms etc.

### CODE REVIEW

**Comment by johnlpage** [comment]
Ok, that's cool

**Comment by tjworks** [comment]
Didn't notice your comments in my previously closed PR before I submitted this new one. My implementation only added a few more counters so I believe it may not add much memory overhead.

**Comment by johnlpage** [comment]
OK, that works

**Comment by johnlpage** [comment]
Merged but had to fix a but in CSV output with -o missing a comma

**Pull request merged**
