### PR TITLE
Add K and I operations

### PR DESCRIPTION
**Pull request by imthereddwarf**
Add two new operations for a -v pipeline 
K generate key value without query,
I perform a $inc operation

### CODE REVIEW

**Comment by johnlpage** [comment]
What's the benefit/use case for these?

**Comment by imthereddwarf** [comment]
For testing an iot scenario, usage data arrives and is accumulated for the
month. Whether $inc versus $set makes much difference is debatable, but an
atomic update rather than a fetch and then update is significant. In the
specific  scenario I am investigating each device will perform three
updates in a group so I am testing KIIII.

In my first round of testing KI was 10% faster than ku.

Pete

**Comment by johnlpage** [comment]
I should start by saying that's for working on this, I don't normally debate PR's but I'm trying to keep POCDriver as focussed as possible. I absolutely get the Update without previous fetch idea, although that's not how I envisioned these workflow options if you need to simulate an update then other steps it makes sense.

I think the increment option is much less valid, an update is an update generally has to read and write the whole document to cache anyway and it opens up people wanting to make this a general purpose simulator which it's not.  Is there a difference between Ku and Ki ?

**Comment by johnlpage** [comment]
Also KIII ? - you might want to reach out directly but if the update/I isn't retrieving the document in between (i.e. not using findOneAndUpdate which I don't think -v will do) what's the business logic to three distinct updates to the same document without reading it between and can they be combined. A lot of older uncombinable ops like $push/$pull have workarounds now.

**Pull request merged**
